# Generated by Django 4.0.6 on 2024-11-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
