# Generated by Django 4.0.6 on 2025-10-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0012_alter_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
